---
title: "Shiny Crude Oil Forecast App"
output: 
  flexdashboard::flex_dashboard:
    logo: 'img/business-science-logo.png'
    orientation: columns
    vertical_layout: fill
    css: ['www/mytheme.css', 'www/styles.css']
runtime: shiny
---

```{r setup, include=FALSE}
# LEARN TO MAKE SHINY APPS AT BUSINESS SCIENCE
# - APP GALLERY: https://apps.business-science.io/

# Shiny
library(flexdashboard)
library(shiny)

# API
library(Quandl)
library(config)

# Time Series
library(lubridate)
library(tsibble)
library(fable)
library(slider)

# Visualization
library(plotly)

# Modeling
library(recipes)
library(rsample)

# Core
library(tidyverse)
library(tidyquant)

# Params
start_date <- "2000-01-01"
end_date   <- today() %>% as.character()
initial_forecast_horizon <- 6

# Set API Key
# Quandl.api_key("your_api_key")
config::get("quandl", file = "../config.yml") %>% Quandl.api_key()

# Helper Functions
api_download <- function(code,
                         src         = c("quandl", "stocks"),
                         value_name  = "Value", 
                         start_date  = "2000-01-01", 
                         end_date    = lubridate::today(),
                         summary_fun = median) {
    
    src <- src[1]
    
    if (src == "quandl") {
        data <- Quandl(code, 
                       start_date = start_date, 
                       end_date   = end_date, 
                       order      = "asc") %>%
            as_tsibble(index = "Date") %>%
            index_by(year_month = yearmonth(Date)) %>%
            summarise(!! value_name := summary_fun(Value))
            
    } else {
        data <- tq_get(code, from = start_date, to = end_date) %>%
            as_tsibble(index = "date") %>%
            select(date, adjusted) %>%
            index_by(year_month = yearmonth(date)) %>%
            rename(Value = adjusted) %>%
            summarise(!! value_name := summary_fun(Value))
    }
    
    return(data)
         
}

# Load Data
wti_spot_prices_tsbl <- api_download(
    code        = "EIA/PET_RWTC_D", 
    src         = "quandl",
    start_date  = start_date, 
    end_date    = end_date, 
    value_name  = "price_wti", 
    summary_fun = first)

financial_arca_tsbl <- api_download(
    code        = "^XOI", 
    src         = "stocks",
    start_date  = start_date, 
    end_date    = end_date, 
    value_name  = "financial_arca", 
    summary_fun = first)

stock_us_refineries_tsbl <- api_download(
    code = "EIA/PET_MCRRSUS1_M", 
    src         = "quandl",
    start_date  = start_date, 
    end_date    = end_date, 
    value_name  = "stock_us_refineries", 
    summary_fun = first)

# Join Data
us_petroleum_joined_m_tsbl <- wti_spot_prices_tsbl %>%
    left_join(stock_us_refineries_tsbl) %>%
    left_join(financial_arca_tsbl)

# CARDS
info_card <- function(title, value, sub_value,
                      main_icon = "chart-line", sub_icon = "arrow-up",
                      bg_color = "default", text_color = "default", 
                      sub_text_color = "success") {
    
    div(
        class = "panel panel-default",
        style = "padding: 0px;",
        div(
            class = str_glue("panel-body bg-{bg_color} text-{text_color}"),
            p(class = "pull-right", icon(class = "fa-4x", main_icon)),
            h4(title),
            h5(value),
            p(
                class = str_glue("text-{sub_text_color}"),
                icon(sub_icon),
                tags$small(sub_value)
            )
        )
    )
    
}

```

Controls {.sidebar}
----------

```{r}
br()
div(
    class = "text-center",
    "Forecast the price per barrel of WTI Crude Oil, an important economic indicator for many companies and industries connected to fuel and energy products,",
    hr(),
    sliderInput("forecast_horizon", 
                label = h4("Enter WTI Crude Oil Forecast Horizon"), 
                min = 1, max = 12, step = 1, 
                value = initial_forecast_horizon, width = "100%"),
    actionButton("submit_button", "Submit", class = "btn-success"),
    br(),
    hr(),
    "Learn Shiny", 
    br(),
    a(href = "https://www.business-science.io/", 
      class = "btn btn-primary", target="_blank", "Business Science")
    
)

# Setup reactive values list
rv <- reactiveValues()

# Perform ARIMA Modeling
observeEvent(input$submit_button, {
    
    req(input$forecast_horizon)
    
    forecast_horizon <- as.numeric(input$forecast_horizon)
    
    # Compute lags based on forecast horizon
    lag_settings_tbl <- us_petroleum_joined_m_tsbl %>%
        map_dfr(.f = function(x) {
            x %>%
                tail(12) %>%
                is.na() %>%
                sum()
        }) %>%
        pivot_longer(cols = everything()) %>%
        mutate(value = value + forecast_horizon) %>%
        pivot_wider(names_from = "name", values_from = "value")

    rv$lag_settings_tbl <- lag_settings_tbl
    
    
    # Preprocess using lag settings
    preprocessing_rec <- recipe(price_wti ~ ., data = us_petroleum_joined_m_tsbl) %>%
        step_date(year_month, features = c("decimal")) %>%
        step_lag(price_wti,
                 lag = lag_settings_tbl$price_wti) %>%
        step_lag(stock_us_refineries,
                 lag = lag_settings_tbl$stock_us_refineries) %>%
        step_lag(financial_arca,
                 lag = lag_settings_tbl$financial_arca) %>%
        step_rm(stock_us_refineries, financial_arca) %>%
        step_naomit(all_predictors()) %>%
        prep()

    rv$preprocessing_rec <- preprocessing_rec

    us_petroleum_prep_m_tsbl <- preprocessing_rec %>%
        bake(us_petroleum_joined_m_tsbl) %>%
        as_tsibble(index = "year_month")

    rv$us_petroleum_prep_m_tsbl <- us_petroleum_prep_m_tsbl

    # Setup Train/Test
    train_test_splits <- initial_time_split(us_petroleum_prep_m_tsbl, prop = 0.8)
    rv$train_set <- training(train_test_splits)
    rv$test_set  <- testing(train_test_splits)
    
    # Train ARIMA models
    nms <- names(us_petroleum_prep_m_tsbl)

    # ARIMA Formulas
    fm_2 <- as.formula(str_glue("price_wti ~ {nms[4]}"))
    fm_3 <- as.formula(str_glue("price_wti ~ {nms[4]} + {nms[6]}"))
    fm_4 <- as.formula(str_glue("price_wti ~ {nms[4]} + {nms[6]} + {nms[3]}"))
    fm_5 <- as.formula(str_glue("price_wti ~ {nms[4]} + {nms[6]} + {nms[3]} + {nms[5]}"))
    
    formula_key_tbl <- tibble(
        `ARIMA(price_wti)` = "price_wti", 
        `ARIMA(fm_2)`      = str_c("price_wti ~ ", rlang::f_text(fm_2)),
        `ARIMA(fm_3)`      = str_c("price_wti ~ ", rlang::f_text(fm_3)),
        `ARIMA(fm_4)`      = str_c("price_wti ~ ", rlang::f_text(fm_4)),
        `ARIMA(fm_5)`      = str_c("price_wti ~ ", rlang::f_text(fm_5))
    ) %>%
        pivot_longer(cols = everything(), names_to = "formula_id", values_to = "formula_label")
    
    rv$formula_key_tbl <- formula_key_tbl

    model_fit <- training(train_test_splits) %>%
        model(
            ARIMA(price_wti),
            ARIMA(fm_2),
            ARIMA(fm_3),
            ARIMA(fm_4),
            ARIMA(fm_5)
        )

    rv$model_fit <- model_fit

    # Make Predictions
    predictions_tsbl <- forecast(model_fit, testing(train_test_splits))

    rv$predictions_tsbl <- predictions_tsbl

    # Calculate MAE (Accuracy)
    mae_naive <- train_test_splits %>%
        testing() %>%
        as_tibble() %>%
        select(contains("price_wti")) %>%
        summarize(mae = mean(abs(.[[1]] - .[[2]])))
    
    rv$mae_naive <- mae_naive

    prediction_mae_tbl <- predictions_tsbl %>%
        as_tibble() %>%
        select(.model, year_month, price_wti) %>%
        rename(.pred = price_wti) %>%
        mutate(.model = as_factor(.model)) %>%
        left_join(
            us_petroleum_joined_m_tsbl %>%
                as_tibble() %>%
                select(year_month, price_wti)
        ) %>%
        group_by(.model) %>%
      
        mutate(rolling_mae = slide2_dbl(.x = price_wti, 
                                    .y = .pred, 
                                    .f = function(x, y) mean(abs(x - y)), 
                                    .before   = forecast_horizon - 1, 
                                    .step     = 1, 
                                    .complete = TRUE)) %>%
        summarize(
            mae = mean(rolling_mae, na.rm = TRUE)
        ) %>%
        mutate(.model = as.character(.model)) %>%
        left_join(formula_key_tbl, by = c(`.model` = "formula_id"))

    rv$predictions_mae_tbl <- prediction_mae_tbl

    # Select Best Model
    best_model_tbl <- prediction_mae_tbl %>%
        filter(mae == min(mae)) %>%
        slice(1) %>%
        mutate(.model = as.character(.model))

    rv$best_model_tbl <- best_model_tbl
    
    # Retrain on Full Dataset
    final_model_fit <- us_petroleum_prep_m_tsbl %>%
        model(ARIMA(as.formula(best_model_tbl$formula_label)))
    
    rv$final_model_fit <- final_model_fit

    # Make future dataset
    new_data_tsbl <- us_petroleum_joined_m_tsbl %>%
        append_row(n = forecast_horizon, keep_all = TRUE) %>%
        bake(preprocessing_rec, .) %>%
        as_tsibble() %>%
        tail(forecast_horizon)

    rv$new_data_tsbl <- new_data_tsbl
    
    # Make future predictions
    predictions_future_tbl <- final_model_fit %>%
        forecast(new_data_tsbl)

    rv$predictions_future_tbl <- predictions_future_tbl
    
}, ignoreNULL = FALSE)
```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Forecast

```{r}
# predictions_future_tbl %>%
#     hilo(level = c(80)) %>% 
#     unnest(cols = c(`80%`), names_sep = "_") %>%
#     as_tsibble(index = year_month) %>%
#     bind_rows(us_petroleum_joined_m_tsbl)

div(
    class = "row",
    div(
        class = "col-md-4",
        uiOutput("card_1")
    ),
    div(
        class = "col-md-4",
        uiOutput("card_2")
    ),
    div(
        class = "col-md-4",
        uiOutput("card_3")
    )
)

div(
    class = "row",
    div(
        class = "col-sm-12",
        div(
            class = "panel",
            div(class = "panel-heading", h5("Forecast")),
            div(class = "panel-body", plotlyOutput(outputId = "plot_fullseries")) 
        )
    )
    
)

output$card_1 <- renderUI({
  
    req(rv$mae_naive, rv$best_model_tbl)
    
    mae_naive <- rv$mae_naive$mae
    mae_model <- rv$best_model_tbl$mae
    
    improvement_percent <- 1 - mae_model / mae_naive 
  
    info_card(
        title = scales::percent(improvement_percent), 
        value = "Reduction in Forecast Error", 
        sub_value = str_glue("{round(mae_model, 2)} Model Error vs {round(mae_naive, 2)} Baseline"),
        main_icon = "chart-line", 
        sub_icon = ifelse(improvement_percent > 0, "arrow-down", "arrow-up"), 
        bg_color = "primary", 
        text_color = "primary", 
        sub_text_color = ifelse(improvement_percent > 0, "success", "danger"))
})

output$card_2 <- renderUI({
  
    req(rv$best_model_tbl)
    
    mae_model <- rv$best_model_tbl$mae
  
    info_card(
        title = scales::dollar(mae_model), 
        value = "Mean Absolute Error (MAE)", 
        sub_value = "ARIMA Model",
        main_icon = "chart-line", 
        sub_icon = NULL, 
        bg_color = "primary", 
        text_color = "primary", 
        sub_text_color = "success")
})

output$card_3 <- renderUI({
  
    req(rv$mae_naive)
    
    mae_naive <- rv$mae_naive$mae
  
    info_card(
        title = scales::dollar(mae_naive), 
        value = "Mean Absolute Error (MAE)", 
        sub_value = "Baseline Model",
        main_icon = "chart-line", 
        sub_icon = NULL, 
        bg_color = "primary", 
        text_color = "primary", 
        sub_text_color = "warning")
})

output$plot_fullseries <- renderPlotly({
  
    rv$predictions_future_tbl
    
    g <- rv$predictions_future_tbl %>%
        select(.model:.distribution) %>%
        mutate(.model = as_factor(.model)) %>%
        hilo(level = c(80)) %>%
        unnest(cols = `80%`) %>%
        # rename(.pred = price_wti) %>%
        bind_rows(
            us_petroleum_joined_m_tsbl
        ) %>%
        arrange(year_month) %>%
        mutate(.model = as.character(.model)) %>%
        mutate(.model = ifelse(is.na(.model), "Actual", .model)) %>%
        mutate(.model = as_factor(.model)) %>%
        
        ggplot(aes(year_month, price_wti, color = .model)) +
        geom_ribbon(aes(ymin = .lower, ymax = .upper), alpha = 0.25, color = NA) +
        geom_line() +
        scale_y_continuous(labels = scales::dollar_format()) + 
        expand_limits(y = 0) +
        scale_color_tq() + 
        labs(x = "", y = "") +
        theme_tq()
    
    ggplotly(g) %>%
        layout(
            xaxis = list(rangeslider = list(visible = T)),
            legend = list(orientation = 'h')
        )
})

```

### ARIMA Models

```{r}
# Debugging
div(
    class = "row",
    div(
        class = "col-md-5",
        div(
            class = "panel", 
            style = "height:750px;;overflow:scroll;",
            div(class = "panel-heading", 
                h5("All Models", br(), tags$small("Performance on Out of Sample Test Set"))),
            div(class = "panel-body", plotlyOutput("all_models", width = "100%", height = "1000px")) 
        )
    ),
    div(
        class = "col-md-7",
        div(
            class = "panel",
            style = "height:750px;overflow:scroll;",
            div(class = "panel-heading", 
                h5("Model Stats", br(), tags$small("Model performance summary"))),
            div(class = "panel-body", verbatimTextOutput("arima_stats")) 
        )
    )
    
)

output$all_models <- renderPlotly({
    
    req(rv$predictions_tsbl, rv$test_set)
    
    g <- rv$predictions_tsbl %>% 
        select(.model:.distribution) %>%
        mutate(.model = as_factor(.model)) %>%
        hilo(level = c(80)) %>%
        unnest(cols = `80%`) %>%
        rename(.pred = price_wti) %>%
        left_join(rv$test_set) %>%
    
        ggplot(aes(year_month, .pred, color = .model, fill = .level)) +
        geom_line(aes(y = price_wti), color = "black") +
        geom_ribbon(aes(ymin = .lower, ymax = .upper), alpha = 0.25, color = NA) +
        geom_line() +
        facet_wrap(~ .model, ncol = 1) +
        
        scale_color_tq() +
        scale_y_continuous(labels = scales::dollar_format()) +
        labs(x = "", y = "") +
        theme_tq() +
        theme(legend.position = "none", 
              strip.text = element_text(margin = margin(t = 5)))
    
    
    ggplotly(g, height = 1000) %>%
        layout(
            showlegend = FALSE,
            xaxis = list(rangeslider = list(visible = T))
        )
})

output$arima_stats <- renderPrint({
    list(
        best_model_tbl         = rv$best_model_tbl,
        mae_naive              = rv$mae_naive,
        predictions_mae_tbl    = rv$predictions_mae_tbl,
        lag_settings_tbl       = rv$lag_settings_tbl,
        formula_key_tbl        = rv$formula_key_tbl,
        model_fit              = rv$model_fit
    )
})
```





